// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth.post').default>>>>
    }
    '/api/routes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routes').default>>>>
    }
    '/api/routes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routes/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routes/[id].put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}